### ISSUE TITLE
Spacy2folia fails

### ISSUE THREAD

**Issue by martinreynaert** [proycon/spacy2folia#2]
Hi,

I try to run spacy2folia and it fails. Here's my command and the stderr:

``
(LMdev) reynaert@violet:SPACY$ spacy2folia -m en_core_web_sm RUSSELL-PhilosophicalEssays.01.folia.xml
Traceback (most recent call last):
  File "/home/reynaert/LMdev/bin/spacy2folia", line 5, in <module>
    from spacy2folia.spacy2folia import main
  File "/home/reynaert/LMdev/lib/python3.9/site-packages/spacy2folia/spacy2folia.py", line 3, in <module>
    import spacy
  File "/home/reynaert/LMdev/lib/python3.9/site-packages/spacy/__init__.py", line 14, in <module>
    from .cli.info import info  # noqa: F401
  File "/home/reynaert/LMdev/lib/python3.9/site-packages/spacy/cli/__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
  File "/home/reynaert/LMdev/lib/python3.9/site-packages/spacy/cli/_util.py", line 8, in <module>
    import typer
  File "/home/reynaert/LMdev/lib/python3.9/site-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/reynaert/LMdev/lib/python3.9/site-packages/click/termui.py)
``

Please help, I am working towards a deadline...

I reran a much older command line which then worked: it fails in the same way now. 

Thank you!

**Comment by proycon** [comment]
Was due to conflicting dependency versions on @martinreynaert 's system. Has been solved now with a downgrade of spacy.
